-- MySQL Script generated by MySQL Workbench
-- 03/17/16 21:41:30
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema sognare
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema sognare
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sognare` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `sognare` ;

-- -----------------------------------------------------
-- Table `sognare`.`Profile`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sognare`.`Profile` (
  `id` INT UNSIGNED NOT NULL COMMENT '',
  `name` VARCHAR(20) NOT NULL COMMENT '',
  `level` INT UNSIGNED NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  UNIQUE INDEX `name_UNIQUE` (`name` ASC)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sognare`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sognare`.`User` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  `profile_id` INT UNSIGNED NOT NULL COMMENT '',
  `email` VARCHAR(100) NOT NULL COMMENT '',
  `password` VARCHAR(50) NOT NULL COMMENT '',
  `enabled` TINYINT(1) NOT NULL DEFAULT 1 COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  UNIQUE INDEX `email_UNIQUE` (`email` ASC)  COMMENT '',
  INDEX `profile_id_FK` (`profile_id` ASC)  COMMENT '',
  CONSTRAINT `User_Profile_FK`
    FOREIGN KEY (`profile_id`)
    REFERENCES `sognare`.`Profile` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sognare`.`Customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sognare`.`Customer` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  `user_id` INT UNSIGNED NULL COMMENT '',
  `name` VARCHAR(100) NOT NULL COMMENT '',
  `phone` VARCHAR(15) NULL COMMENT '',
  `birth_date` DATE NULL COMMENT '',
  `enabled` TINYINT(1) NOT NULL DEFAULT 1 COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `user_id_FK` (`user_id` ASC)  COMMENT '',
  UNIQUE INDEX `phone_UNIQUE` (`phone` ASC)  COMMENT '',
  CONSTRAINT `Customer_User_FK`
    FOREIGN KEY (`user_id`)
    REFERENCES `sognare`.`User` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sognare`.`CustomerAddress`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sognare`.`CustomerAddress` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  `customer_id` INT UNSIGNED NOT NULL COMMENT '',
  `zip_code` VARCHAR(8) NOT NULL COMMENT '',
  `address` VARCHAR(255) NOT NULL COMMENT '',
  `number` INT NULL COMMENT '',
  `complement` VARCHAR(50) NULL COMMENT '',
  `neighborhood` VARCHAR(50) NOT NULL COMMENT '',
  `city` VARCHAR(50) NOT NULL COMMENT '',
  `acronym_city` CHAR(2) NOT NULL COMMENT '',
  `reference_point` VARCHAR(100) NULL COMMENT '',
  `latitude` DECIMAL(10,8) NULL COMMENT '',
  `longitude` DECIMAL(10,8) NULL COMMENT '',
  `enabled` TINYINT(1) NOT NULL DEFAULT 1 COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `customer_id_FK` (`customer_id` ASC)  COMMENT '',
  CONSTRAINT `CustomerAddress_Customer_FK`
    FOREIGN KEY (`customer_id`)
    REFERENCES `sognare`.`Customer` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sognare`.`Ingredient`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sognare`.`Ingredient` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  `name` VARCHAR(50) NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  UNIQUE INDEX `name_UNIQUE` (`name` ASC)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sognare`.`DrinkType`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sognare`.`DrinkType` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  `name` VARCHAR(50) NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  UNIQUE INDEX `name_UNIQUE` (`name` ASC)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sognare`.`Drink`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sognare`.`Drink` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  `drink_type_id` INT UNSIGNED NOT NULL COMMENT '',
  `name` VARCHAR(50) NOT NULL COMMENT '',
  `price` DECIMAL(15,2) NOT NULL COMMENT '',
  `image` VARCHAR(255) NULL COMMENT '',
  `enabled` TINYINT(1) NOT NULL DEFAULT 1 COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `drink_type_id_FK` (`drink_type_id` ASC)  COMMENT '',
  UNIQUE INDEX `name_UNIQUE` (`name` ASC)  COMMENT '',
  CONSTRAINT `Drink_DrinkType_FK`
    FOREIGN KEY (`drink_type_id`)
    REFERENCES `sognare`.`DrinkType` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sognare`.`PizzaFlavor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sognare`.`PizzaFlavor` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  `name` VARCHAR(50) NOT NULL COMMENT '',
  `image` VARCHAR(255) NULL COMMENT '',
  `enabled` TINYINT(1) NOT NULL DEFAULT 1 COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  UNIQUE INDEX `name_UNIQUE` (`name` ASC)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sognare`.`PizzaSize`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sognare`.`PizzaSize` (
  `id` INT UNSIGNED NOT NULL COMMENT '',
  `name` VARCHAR(50) NOT NULL COMMENT '',
  `size` INT NOT NULL COMMENT '',
  `slices` INT NOT NULL COMMENT '',
  `price` DECIMAL(15,2) NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  UNIQUE INDEX `name_UNIQUE` (`name` ASC)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sognare`.`PizzaFlavorIngredient`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sognare`.`PizzaFlavorIngredient` (
  `pizza_flavor_id` INT UNSIGNED NOT NULL COMMENT '',
  `ingredient_id` INT UNSIGNED NOT NULL COMMENT '',
  PRIMARY KEY (`pizza_flavor_id`, `ingredient_id`)  COMMENT '',
  INDEX `ingredient_id_FK` (`ingredient_id` ASC)  COMMENT '',
  INDEX `pizza_flavor_id_FK` (`pizza_flavor_id` ASC)  COMMENT '',
  CONSTRAINT `PizzaFlavorIngredient_PizzaFlavor_FK`
    FOREIGN KEY (`pizza_flavor_id`)
    REFERENCES `sognare`.`PizzaFlavor` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `PizzaFlavorIngredient_Ingredient_FK`
    FOREIGN KEY (`ingredient_id`)
    REFERENCES `sognare`.`Ingredient` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sognare`.`Pizza`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sognare`.`Pizza` (
  `id` INT UNSIGNED ZEROFILL NOT NULL COMMENT '',
  `pizza_flavor_id` INT UNSIGNED NOT NULL COMMENT '',
  `pizza_size_id` INT UNSIGNED NOT NULL COMMENT '',
  `price` DECIMAL(15,2) NOT NULL COMMENT '',
  `enabled` TINYINT(1) NOT NULL DEFAULT 1 COMMENT '',
  INDEX `pizza_size_id_FK` (`pizza_size_id` ASC)  COMMENT '',
  INDEX `pizza_flavor_id_FK` (`pizza_flavor_id` ASC)  COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  CONSTRAINT `Pizza_PizzaFlavor_FK`
    FOREIGN KEY (`pizza_flavor_id`)
    REFERENCES `sognare`.`PizzaFlavor` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Pizza_PizzaSize_FK`
    FOREIGN KEY (`pizza_size_id`)
    REFERENCES `sognare`.`PizzaSize` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sognare`.`PaymentType`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sognare`.`PaymentType` (
  `id` INT NOT NULL COMMENT '',
  `name` VARCHAR(50) NOT NULL COMMENT '',
  `enabled` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  UNIQUE INDEX `name_UNIQUE` (`name` ASC)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sognare`.`Order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sognare`.`Order` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  `balcony` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '',
  `payment_type_id` INT NOT NULL COMMENT '',
  `customer_address_id` INT UNSIGNED NULL COMMENT '',
  `price` DECIMAL(15,2) NOT NULL COMMENT '',
  `discount` DECIMAL(15,2) NOT NULL DEFAULT 0.00 COMMENT '',
  `final_price` DECIMAL(15,2) NOT NULL COMMENT '',
  `change` DECIMAL(15,2) NOT NULL DEFAULT 0.00 COMMENT '',
  `delivery_price` DECIMAL(15,2) NOT NULL DEFAULT 0.00 COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `payment_type_id_FK` (`payment_type_id` ASC)  COMMENT '',
  INDEX `orders_customer_address_id_FK` (`customer_address_id` ASC)  COMMENT '',
  CONSTRAINT `Order_PaymentType_FK`
    FOREIGN KEY (`payment_type_id`)
    REFERENCES `sognare`.`PaymentType` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Order_CustomerAddress_FK`
    FOREIGN KEY (`customer_address_id`)
    REFERENCES `sognare`.`CustomerAddress` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sognare`.`OrderPizza`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sognare`.`OrderPizza` (
  `order_id` INT UNSIGNED NOT NULL COMMENT '',
  `pizza_id` INT UNSIGNED ZEROFILL NOT NULL COMMENT '',
  PRIMARY KEY (`order_id`, `pizza_id`)  COMMENT '',
  INDEX `pizza_id_FK` (`pizza_id` ASC)  COMMENT '',
  INDEX `order_id_FK` (`order_id` ASC)  COMMENT '',
  CONSTRAINT `OrderPizza_Order_FK`
    FOREIGN KEY (`order_id`)
    REFERENCES `sognare`.`Order` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `OrderPizza_Pizza_FK`
    FOREIGN KEY (`pizza_id`)
    REFERENCES `sognare`.`Pizza` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sognare`.`OrderDrink`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sognare`.`OrderDrink` (
  `order_id` INT UNSIGNED NOT NULL COMMENT '',
  `drink_id` INT UNSIGNED NOT NULL COMMENT '',
  PRIMARY KEY (`order_id`, `drink_id`)  COMMENT '',
  INDEX `drink_id_FK` (`drink_id` ASC)  COMMENT '',
  INDEX `order_id_FK` (`order_id` ASC)  COMMENT '',
  CONSTRAINT `OrdersDrink_Order_FK`
    FOREIGN KEY (`order_id`)
    REFERENCES `sognare`.`Order` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `OrdersDrink_Drink_FK`
    FOREIGN KEY (`drink_id`)
    REFERENCES `sognare`.`Drink` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sognare`.`OrderStatus`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sognare`.`OrderStatus` (
  `id` INT UNSIGNED NOT NULL COMMENT '',
  `description` VARCHAR(50) NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  UNIQUE INDEX `description_UNIQUE` (`description` ASC)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sognare`.`OrderLog`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sognare`.`OrderLog` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  `order_id` INT UNSIGNED NOT NULL COMMENT '',
  `order_status_id` INT UNSIGNED NOT NULL COMMENT '',
  `user_id` INT UNSIGNED NOT NULL COMMENT '',
  `note` VARCHAR(100) NULL COMMENT '',
  `order_log_datetime` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `order_id_FK` (`order_id` ASC)  COMMENT '',
  INDEX `order_status_id_FK` (`order_status_id` ASC)  COMMENT '',
  UNIQUE INDEX `order_id_order_status_id_UNIQUE` (`order_id` ASC, `order_status_id` ASC)  COMMENT '',
  INDEX `user_id_FK` (`user_id` ASC)  COMMENT '',
  CONSTRAINT `OrderLog_Order_FK`
    FOREIGN KEY (`order_id`)
    REFERENCES `sognare`.`Order` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `OrderLog_OrderStatus_FK`
    FOREIGN KEY (`order_status_id`)
    REFERENCES `sognare`.`OrderStatus` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `OrderLog_User_FK`
    FOREIGN KEY (`user_id`)
    REFERENCES `sognare`.`User` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sognare`.`Employer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sognare`.`Employer` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  `user_id` INT UNSIGNED NULL COMMENT '',
  `name` VARCHAR(255) NOT NULL COMMENT '',
  `phone` VARCHAR(15) NULL COMMENT '',
  `enabled` TINYINT(1) NOT NULL DEFAULT 1 COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `user_id_FK` (`user_id` ASC)  COMMENT '',
  CONSTRAINT `Employer_User_FK`
    FOREIGN KEY (`user_id`)
    REFERENCES `sognare`.`User` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sognare`.`ZipCode`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sognare`.`ZipCode` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  `zip_code` VARCHAR(8) NOT NULL COMMENT '',
  `delivery_price` DECIMAL(15,2) NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  UNIQUE INDEX `zip_code_UNIQUE` (`zip_code` ASC)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sognare`.`CakeType`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sognare`.`CakeType` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  `name` VARCHAR(50) NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  UNIQUE INDEX `name_UNIQUE` (`name` ASC)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sognare`.`Cake`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sognare`.`Cake` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  `cake_type_id` INT UNSIGNED NOT NULL COMMENT '',
  `name` VARCHAR(50) NOT NULL COMMENT '',
  `price` DECIMAL(15,2) NOT NULL COMMENT '',
  `image` VARCHAR(255) NULL COMMENT '',
  `enabled` TINYINT(1) NOT NULL DEFAULT 1 COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  UNIQUE INDEX `name_UNIQUE` (`name` ASC)  COMMENT '',
  INDEX `cake_type_id_FK` (`cake_type_id` ASC)  COMMENT '',
  CONSTRAINT `Cake_CakeType_FK`
    FOREIGN KEY (`cake_type_id`)
    REFERENCES `sognare`.`CakeType` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sognare`.`OrderCake`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sognare`.`OrderCake` (
  `order_id` INT UNSIGNED NOT NULL COMMENT '',
  `cake_id` INT UNSIGNED NOT NULL COMMENT '',
  PRIMARY KEY (`order_id`, `cake_id`)  COMMENT '',
  INDEX `cake_id_FK` (`cake_id` ASC)  COMMENT '',
  INDEX `order_id_FK` (`order_id` ASC)  COMMENT '',
  CONSTRAINT `OrderCake_Order_FK`
    FOREIGN KEY (`order_id`)
    REFERENCES `sognare`.`Order` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `OrderCake_Cake_FK`
    FOREIGN KEY (`cake_id`)
    REFERENCES `sognare`.`Cake` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `sognare`.`Profile`
-- -----------------------------------------------------
START TRANSACTION;
USE `sognare`;
INSERT INTO `sognare`.`Profile` (`id`, `name`, `level`) VALUES (1, 'Cliente', 10);
INSERT INTO `sognare`.`Profile` (`id`, `name`, `level`) VALUES (2, 'Entregador', 20);
INSERT INTO `sognare`.`Profile` (`id`, `name`, `level`) VALUES (3, 'Atendente', 30);
INSERT INTO `sognare`.`Profile` (`id`, `name`, `level`) VALUES (4, 'Gerente', 40);
INSERT INTO `sognare`.`Profile` (`id`, `name`, `level`) VALUES (5, 'Administrador', 50);

COMMIT;


-- -----------------------------------------------------
-- Data for table `sognare`.`User`
-- -----------------------------------------------------
START TRANSACTION;
USE `sognare`;
INSERT INTO `sognare`.`User` (`id`, `profile_id`, `email`, `password`, `enabled`) VALUES (1, 5, 'alexsilvamartinsasm@gmail.com', 'e10adc3949ba59abbe56e057f20f883e', 1);

COMMIT;


-- -----------------------------------------------------
-- Data for table `sognare`.`PizzaSize`
-- -----------------------------------------------------
START TRANSACTION;
USE `sognare`;
INSERT INTO `sognare`.`PizzaSize` (`id`, `name`, `size`, `slices`, `price`) VALUES (1, 'Pequena', 25, 6, DEFAULT);
INSERT INTO `sognare`.`PizzaSize` (`id`, `name`, `size`, `slices`, `price`) VALUES (2, 'Família', 35, 8, DEFAULT);
INSERT INTO `sognare`.`PizzaSize` (`id`, `name`, `size`, `slices`, `price`) VALUES (3, 'Gigante', 45, 10, DEFAULT);

COMMIT;


-- -----------------------------------------------------
-- Data for table `sognare`.`PaymentType`
-- -----------------------------------------------------
START TRANSACTION;
USE `sognare`;
INSERT INTO `sognare`.`PaymentType` (`id`, `name`, `enabled`) VALUES (1, 'Dinheiro', DEFAULT);

COMMIT;


-- -----------------------------------------------------
-- Data for table `sognare`.`OrderStatus`
-- -----------------------------------------------------
START TRANSACTION;
USE `sognare`;
INSERT INTO `sognare`.`OrderStatus` (`id`, `description`) VALUES (1, 'Aberto');
INSERT INTO `sognare`.`OrderStatus` (`id`, `description`) VALUES (2, 'Em produção');
INSERT INTO `sognare`.`OrderStatus` (`id`, `description`) VALUES (3, 'Pronto');
INSERT INTO `sognare`.`OrderStatus` (`id`, `description`) VALUES (4, 'Em entrega');
INSERT INTO `sognare`.`OrderStatus` (`id`, `description`) VALUES (5, 'Entregue');
INSERT INTO `sognare`.`OrderStatus` (`id`, `description`) VALUES (6, 'Cancelado');
INSERT INTO `sognare`.`OrderStatus` (`id`, `description`) VALUES (7, 'Fechado');

COMMIT;

